Repository fabuxorg/DiscordBot-Framework, pull requests merged in 2019-12, with the labels that each got.

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement, major

#22 #18 plugin version control
  README.md
  src/main/java/org/fabux/discordbotframework/Main.java
  src/main/java/org/fabux/discordbotframework/util/versionhandler/VersionHandler.java
Labels: Urgent, documentation, enhancement, major

#27 17 log in file
  .gradle/5.2.1/executionHistory/executionHistory.bin
  .gradle/5.2.1/executionHistory/executionHistory.lock
  .gradle/5.2.1/fileContent/fileContent.lock
  .gradle/5.2.1/fileHashes/fileHashes.bin
  .gradle/5.2.1/fileHashes/fileHashes.lock
  .gradle/5.2.1/javaCompile/classAnalysis.bin
  .gradle/5.2.1/javaCompile/javaCompile.lock
  .gradle/5.2.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  build/resources/main/version.txt
  src/main/java/org/fabux/discordbotframework/Main.java
  src/main/java/org/fabux/discordbotframework/datahandler/database/mongodb/MongoDBHandler.java
  src/main/java/org/fabux/discordbotframework/datahandler/filehandler/FileHelper.java
  src/main/java/org/fabux/discordbotframework/datahandler/filehandler/WriteFile.java
  src/main/java/org/fabux/discordbotframework/datahandler/filehandler/config/ConfigReader.java
  src/main/java/org/fabux/discordbotframework/datahandler/filehandler/config/ConfigWriter.java
  src/main/java/org/fabux/discordbotframework/util/initBot/HandleOnlineStatus.java
  src/main/java/org/fabux/discordbotframework/util/initBot/InitBot.java
  src/main/java/org/fabux/discordbotframework/util/logs/Logger.java
  src/main/java/org/fabux/discordbotframework/util/time/Time.java
  src/main/java/org/fabux/discordbotframework/util/versionhandler/VersionHandler.java
Labels: Urgent, enhancement, major

#29 Create Logo.png
  Logo.png
Labels: UI, enhancement

#28 #26 updated version
  .gradle/5.2.1/executionHistory/executionHistory.bin
  .gradle/5.2.1/executionHistory/executionHistory.lock
  .gradle/5.2.1/fileHashes/fileHashes.bin
  .gradle/5.2.1/fileHashes/fileHashes.lock
  .gradle/5.2.1/javaCompile/classAnalysis.bin
  .gradle/5.2.1/javaCompile/javaCompile.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
Labels: enhancement

#33 added Logo to README
  README.md
Labels: documentation

#32 updated jda #31
  build.gradle
Labels: Urgent, enhancement, major
